#!/usr/bin/env node
import { Command } from "commander";
import inquirer from "inquirer";
import * as fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { spawn } from "node:child_process";

let apiBase = process.env.KCM_API_URL || "http://127.0.0.1:4173/api";
const FRAMEWORKS = ["react", "vue", "vanilla"];

function toKebabCase(input) {
  return String(input || "")
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[\s_]+/g, "-")
    .replace(/[^a-zA-Z0-9-]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase();
}

function toPascalCase(input) {
  return toKebabCase(input)
    .split("-")
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

function normalizeFramework(input) {
  const raw = String(input || "").trim().toLowerCase();
  if (!raw) return "";
  if (raw.includes("react")) return "react";
  if (raw.includes("vue")) return "vue";
  if (raw.includes("vanilla")) return "vanilla";
  return raw;
}

function run(command, args, options = {}) {
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      stdio: "inherit",
      shell: false,
      ...options
    });

    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) resolve();
      else reject(new Error(`Command failed (${code}): ${command} ${args.join(" ")}`));
    });
  });
}

async function pathExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function request(path, options = {}) {
  const response = await fetch(`${apiBase}${path}`, options);
  let body = null;
  try {
    body = await response.json();
  } catch {
    body = null;
  }

  if (!response.ok || !body?.ok) {
    const reason = body?.error || `Request failed (${response.status})`;
    throw new Error(reason);
  }
  return body;
}

async function createComponent({ framework, component, version, author, number }) {
  const body = await request("/components", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ framework, component, version, author, number })
  });
  console.log(`Created ${framework}/${component}`);
  console.log(`Files: ${body.files.join(", ")}`);
}

async function listComponents() {
  const body = await request("/components");
  const frameworks = Object.keys(body.components);
  for (const fw of frameworks) {
    const items = body.components[fw] || [];
    console.log(`${fw}: ${items.length ? items.join(", ") : "(none)"}`);
  }
}

async function deleteComponent(framework, component) {
  await request(`/components/${framework}/${component}`, { method: "DELETE" });
  console.log(`Deleted ${framework}/${component}`);
}

async function scaffoldReactViteProject(projectDir, projectName, { useTypeScript }) {
  const pkg = {
    name: projectName,
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "vite build",
      preview: "vite preview"
    },
    dependencies: {
      react: "^18.3.1",
      "react-dom": "^18.3.1"
    },
    devDependencies: {
      vite: "^5.4.0",
      "@vitejs/plugin-react": "^4.3.0"
    }
  };

  const mainExt = useTypeScript ? "tsx" : "jsx";
  const appExt = useTypeScript ? "tsx" : "jsx";
  const viteConfig = `import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

export default defineConfig({
  plugins: [react()]
});
`;

  const indexHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.${mainExt}"></script>
  </body>
</html>
`;

  const mainSource = `import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.${appExt}";
import "./index.css";

ReactDOM.createRoot(document.getElementById("root")).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
`;

  const appSource = `export default function App() {
  return (
    <main style={{ padding: 16, fontFamily: "system-ui, sans-serif" }}>
      <h1>${projectName}</h1>
      <p>Generated by kcm.</p>
    </main>
  );
}
`;

  const css = `:root {
  color-scheme: light dark;
}

body {
  margin: 0;
}
`;

  await fs.mkdir(path.join(projectDir, "src"), { recursive: true });

  if (useTypeScript) {
    pkg.devDependencies.typescript = "^5.6.0";
    pkg.devDependencies["@types/react"] = "^18.3.0";
    pkg.devDependencies["@types/react-dom"] = "^18.3.0";
  }

  await fs.writeFile(path.join(projectDir, "package.json"), JSON.stringify(pkg, null, 2) + "\n", "utf8");
  await fs.writeFile(path.join(projectDir, "vite.config.js"), viteConfig, "utf8");
  await fs.writeFile(path.join(projectDir, "index.html"), indexHtml, "utf8");
  await fs.writeFile(path.join(projectDir, "src", `main.${mainExt}`), mainSource, "utf8");
  await fs.writeFile(path.join(projectDir, "src", `App.${appExt}`), appSource, "utf8");
  await fs.writeFile(path.join(projectDir, "src", "index.css"), css, "utf8");

  if (useTypeScript) {
    const tsconfig = `{
  "compilerOptions": {
    "target": "ES2020",
    "useDefineForClassFields": true,
    "lib": ["ES2020", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true
  },
  "include": ["src"]
}
`;
    const envDts = `/// <reference types="vite/client" />
`;
    await fs.writeFile(path.join(projectDir, "tsconfig.json"), tsconfig, "utf8");
    await fs.writeFile(path.join(projectDir, "src", "vite-env.d.ts"), envDts, "utf8");
  }

  await fs.writeFile(path.join(projectDir, ".gitignore"), "node_modules\n.DS_Store\ndist\n.env\n", "utf8");
}

async function scaffoldVueViteProject(projectDir, projectName) {
  const pkg = {
    name: projectName,
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "vite build",
      preview: "vite preview"
    },
    dependencies: {
      vue: "^3.5.0"
    },
    devDependencies: {
      vite: "^5.4.0",
      "@vitejs/plugin-vue": "^5.1.0"
    }
  };

  const viteConfig = `import { defineConfig } from "vite";
import vue from "@vitejs/plugin-vue";

export default defineConfig({
  plugins: [vue()]
});
`;

  const indexHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
`;

  const mainSource = `import { createApp } from "vue";
import App from "./App.vue";
import "./style.css";

createApp(App).mount("#app");
`;

  const appVue = `<script setup>
const name = "${projectName}";
</script>

<template>
  <main class="app">
    <h1>{{ name }}</h1>
    <p>Generated by kcm.</p>
  </main>
</template>

<style scoped>
.app {
  padding: 16px;
  font-family: system-ui, sans-serif;
}
</style>
`;

  const css = `:root {
  color-scheme: light dark;
}

body {
  margin: 0;
}
`;

  await fs.mkdir(path.join(projectDir, "src"), { recursive: true });
  await fs.writeFile(path.join(projectDir, "package.json"), JSON.stringify(pkg, null, 2) + "\n", "utf8");
  await fs.writeFile(path.join(projectDir, "vite.config.js"), viteConfig, "utf8");
  await fs.writeFile(path.join(projectDir, "index.html"), indexHtml, "utf8");
  await fs.writeFile(path.join(projectDir, "src", "main.js"), mainSource, "utf8");
  await fs.writeFile(path.join(projectDir, "src", "App.vue"), appVue, "utf8");
  await fs.writeFile(path.join(projectDir, "src", "style.css"), css, "utf8");
  await fs.writeFile(path.join(projectDir, ".gitignore"), "node_modules\n.DS_Store\ndist\n.env\n", "utf8");
}

async function scaffoldVanillaViteProject(projectDir, projectName) {
  const pkg = {
    name: projectName,
    private: true,
    version: "0.0.0",
    type: "module",
    scripts: {
      dev: "vite",
      build: "vite build",
      preview: "vite preview"
    },
    devDependencies: {
      vite: "^5.4.0"
    }
  };

  const indexHtml = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${projectName}</title>
  </head>
  <body>
    <main id="app"></main>
    <script type="module" src="/src/main.js"></script>
  </body>
</html>
`;

  const mainSource = `import "./style.css";

document.getElementById("app").innerHTML = \`
  <h1>${projectName}</h1>
  <p>Generated by kcm.</p>
\`;
`;

  const css = `:root {
  color-scheme: light dark;
}

body {
  margin: 0;
  padding: 16px;
  font-family: system-ui, sans-serif;
}
`;

  await fs.mkdir(path.join(projectDir, "src"), { recursive: true });
  await fs.writeFile(path.join(projectDir, "package.json"), JSON.stringify(pkg, null, 2) + "\n", "utf8");
  await fs.writeFile(path.join(projectDir, "index.html"), indexHtml, "utf8");
  await fs.writeFile(path.join(projectDir, "src", "main.js"), mainSource, "utf8");
  await fs.writeFile(path.join(projectDir, "src", "style.css"), css, "utf8");
  await fs.writeFile(path.join(projectDir, ".gitignore"), "node_modules\n.DS_Store\ndist\n.env\n", "utf8");
}

async function initGitRepo(repoDir) {
  await run("git", ["init"], { cwd: repoDir });
  await run("git", ["add", "-A"], { cwd: repoDir });
  await run("git", ["commit", "-m", "Initial commit"], { cwd: repoDir });
}

async function createGitHubRepoWithGh(repoDir, repoName, { visibility }) {
  const visibilityFlag = visibility === "public" ? "--public" : "--private";
  await run("gh", ["repo", "create", repoName, visibilityFlag, "--source", ".", "--remote", "origin", "--push", "--confirm"], {
    cwd: repoDir
  });
}

async function wizardCreateProject() {
  const answers = await inquirer.prompt([
    {
      type: "input",
      name: "projectName",
      message: "Project name",
      validate: (v) => (toKebabCase(v) ? true : "Enter a project name.")
    },
    {
      type: "list",
      name: "framework",
      message: "Framework/library",
      choices: [
        { name: "React (Vite template)", value: "react" },
        { name: "Vue (Vite template)", value: "vue" },
        { name: "Vanilla (Vite template)", value: "vanilla" }
      ]
    },
    {
      type: "confirm",
      name: "useTypeScript",
      message: "Use TypeScript?",
      default: false,
      when: (a) => a.framework === "react"
    },
    {
      type: "input",
      name: "parentDir",
      message: "Create in directory",
      default: process.cwd()
    },
    {
      type: "confirm",
      name: "initGit",
      message: "Initialize a local git repo?",
      default: true
    },
    {
      type: "confirm",
      name: "createGitHub",
      message: "Create a GitHub repo and push (requires `gh` auth)?",
      default: false,
      when: (a) => a.initGit
    },
    {
      type: "list",
      name: "visibility",
      message: "GitHub visibility",
      choices: [
        { name: "Private", value: "private" },
        { name: "Public", value: "public" }
      ],
      default: "private",
      when: (a) => a.createGitHub
    }
  ]);

  const rawProjectName = String(answers.projectName || "");
  const projectName = toKebabCase(rawProjectName);
  if (rawProjectName.trim() && rawProjectName.trim() !== projectName) {
    console.log(`Note: "${rawProjectName.trim()}" normalized to "${projectName}"`);
  }
  const framework = normalizeFramework(answers.framework);
  const parentDir = path.resolve(String(answers.parentDir || process.cwd()));
  const projectDir = path.join(parentDir, projectName);

  if (await pathExists(projectDir)) {
    throw new Error(`Directory already exists: ${projectDir}`);
  }

  if (framework === "react") {
    await fs.mkdir(projectDir, { recursive: true });
    await scaffoldReactViteProject(projectDir, projectName, { useTypeScript: Boolean(answers.useTypeScript) });
  } else if (framework === "vue") {
    await fs.mkdir(projectDir, { recursive: true });
    await scaffoldVueViteProject(projectDir, projectName);
  } else if (framework === "vanilla") {
    await fs.mkdir(projectDir, { recursive: true });
    await scaffoldVanillaViteProject(projectDir, projectName);
  } else {
    throw new Error(`Unsupported framework '${framework}'.`);
  }

  if (answers.initGit) {
    try {
      await initGitRepo(projectDir);
    } catch (error) {
      console.warn("Warning: git init/commit failed. Ensure git is installed and user.name/user.email are configured.");
      console.warn(error instanceof Error ? error.message : String(error));
    }
  }

  if (answers.createGitHub) {
    try {
      await createGitHubRepoWithGh(projectDir, projectName, { visibility: answers.visibility });
    } catch (error) {
      console.warn("Warning: GitHub repo creation failed. Ensure `gh` is installed and you have run `gh auth login`.");
      console.warn(error instanceof Error ? error.message : String(error));
    }
  }

  console.log("");
  console.log(`Project created: ${projectDir}`);
  console.log(`Next: cd ${projectName} && npm install && npm run dev`);
}

async function wizardCreateStandaloneComponent() {
  const answers = await inquirer.prompt([
    {
      type: "input",
      name: "componentName",
      message: "Component name",
      validate: (v) => (toKebabCase(v) ? true : "Enter a component name.")
    },
    {
      type: "list",
      name: "framework",
      message: "Framework/library",
      choices: [
        { name: "React", value: "react" },
        { name: "Vue", value: "vue" },
        { name: "Vanilla", value: "vanilla" }
      ]
    },
    {
      type: "input",
      name: "version",
      message: "Version",
      default: "1.0.0"
    },
    {
      type: "input",
      name: "author",
      message: "Author",
      default: "Unknown"
    },
    {
      type: "input",
      name: "number",
      message: "Number",
      default: "N/A"
    }
  ]);

  const rawComponentName = String(answers.componentName || "");
  const componentName = toKebabCase(rawComponentName);
  if (rawComponentName.trim() && rawComponentName.trim() !== componentName) {
    console.log(`Note: "${rawComponentName.trim()}" normalized to "${componentName}"`);
  }
  const framework = normalizeFramework(answers.framework);

  try {
    await createComponent({
      framework,
      component: componentName,
      version: answers.version,
      author: answers.author,
      number: answers.number
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new Error(
      `Failed to create component via API (required for database insert). ${message}\n` +
        `Ensure the API server is running and DATABASE_URL is configured.\n` +
        `Current API base: ${apiBase}`
    );
  }

  console.log("");
  console.log(`Component created and saved to DB: ${framework}/${componentName}`);
}

async function interactiveMode() {
  const { action } = await inquirer.prompt([
    {
      type: "list",
      name: "action",
      message: "What do you want to create?",
      choices: [
        { name: "Create project", value: "project" },
        { name: "Create single component", value: "standalone-component" },
        new inquirer.Separator(),
        { name: "Manage KCM API components (create/list/delete)", value: "api-manage" }
      ]
    }
  ]);

  if (action === "project") {
    await wizardCreateProject();
    return;
  }

  if (action === "standalone-component") {
    await wizardCreateStandaloneComponent();
    return;
  }

  const { apiAction } = await inquirer.prompt([
    {
      type: "list",
      name: "apiAction",
      message: "KCM API action",
      choices: [
        { name: "Create component (API)", value: "create" },
        { name: "List components (API)", value: "list" },
        { name: "Delete component (API)", value: "delete" }
      ]
    }
  ]);

  if (apiAction === "list") {
    await listComponents();
    return;
  }

  if (apiAction === "create") {
    const answers = await inquirer.prompt([
      {
        type: "list",
        name: "framework",
        message: "Framework",
        choices: FRAMEWORKS
      },
      {
        type: "input",
        name: "component",
        message: "Component name",
        validate: (v) => (toKebabCase(v) ? true : "Enter a component name.")
      },
      {
        type: "input",
        name: "version",
        message: "Version",
        default: "1.0.0"
      },
      {
        type: "input",
        name: "author",
        message: "Author",
        default: "Unknown"
      },
      {
        type: "input",
        name: "number",
        message: "Number",
        default: "N/A"
      }
    ]);

    const normalized = toKebabCase(answers.component);
    if (String(answers.component || "").trim() !== normalized) {
      console.log(`Note: "${String(answers.component || "").trim()}" normalized to "${normalized}"`);
    }
    await createComponent({ ...answers, framework: normalizeFramework(answers.framework), component: normalized });
    return;
  }

  const listBody = await request("/components");
  const componentChoices = Object.entries(listBody.components).flatMap(([framework, items]) =>
    (items || []).map((component) => ({
      name: `${framework}/${component}`,
      value: { framework, component }
    }))
  );

  if (!componentChoices.length) {
    console.log("No components available to delete.");
    return;
  }

  const { target } = await inquirer.prompt([
    {
      type: "list",
      name: "target",
      message: "Select component to delete",
      choices: componentChoices
    }
  ]);

  const { confirmed } = await inquirer.prompt([
    {
      type: "confirm",
      name: "confirmed",
      message: `Delete ${target.framework}/${target.component}?`,
      default: false
    }
  ]);

  if (!confirmed) {
    console.log("Cancelled.");
    return;
  }

  await deleteComponent(target.framework, target.component);
}

const program = new Command();
program
  .name("kcm")
  .description("Kaylios Component Manager CLI")
  .option("--api <url>", "API base URL override");

program
  .command("create")
  .requiredOption("-f, --framework <framework>", "framework", (v) => v.toLowerCase())
  .requiredOption("-n, --name <component>", "component name (kebab-case)")
  .option("-v, --version <version>", "version", "1.0.0")
  .option("-a, --author <author>", "author", "Unknown")
  .option("--number <number>", "component number", "N/A")
  .action(async (options) => {
    if (!FRAMEWORKS.includes(options.framework)) {
      throw new Error(`Invalid framework '${options.framework}'. Use: ${FRAMEWORKS.join(", ")}`);
    }
    const normalized = toKebabCase(options.name);
    if (!normalized) throw new Error("Component name is required.");
    if (String(options.name || "").trim() !== normalized) {
      console.log(`Note: "${String(options.name || "").trim()}" normalized to "${normalized}"`);
    }
    await createComponent({
      framework: options.framework,
      component: normalized,
      version: options.version,
      author: options.author,
      number: options.number
    });
  });

program
  .command("list")
  .description("List components")
  .action(async () => {
    await listComponents();
  });

program
  .command("delete")
  .requiredOption("-f, --framework <framework>", "framework")
  .requiredOption("-n, --name <component>", "component name")
  .action(async (options) => {
    const normalized = toKebabCase(options.name);
    if (!normalized) throw new Error("Component name is required.");
    if (String(options.name || "").trim() !== normalized) {
      console.log(`Note: "${String(options.name || "").trim()}" normalized to "${normalized}"`);
    }
    await deleteComponent(options.framework, normalized);
  });

program
  .command("interactive")
  .description("Interactive mode (inquirer)")
  .action(async () => {
    await interactiveMode();
  });

program
  .command("new")
  .description("Create a project or a standalone component (wizard)")
  .action(async () => {
    await interactiveMode();
  });

program.hook("preAction", (thisCommand) => {
  const opts = thisCommand.opts();
  if (opts.api) apiBase = opts.api;
});

(async () => {
  try {
    program.parse(process.argv);
    if (!process.argv.slice(2).length) {
      await interactiveMode();
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  }
})();
